# Generated by Django 4.2 on 2023-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_grade_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.AddField(
            model_name="profile",
            name="grade",
            field=models.TextField(null=True),
        ),
    ]
