# Generated by Django 4.2 on 2023-05-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_grade_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.TextField(null=True),
        ),
    ]
