# Generated by Django 4.2 on 2023-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                related_name="followers", to="accounts.profile"
            ),
        ),
    ]
