# Generated by Django 4.2 on 2023-05-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="weather",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
