# Generated by Django 4.2 on 2023-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_post_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="writer",
            field=models.CharField(max_length=100),
        ),
    ]
