# Generated by Django 4.2 on 2023-05-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_writer_post_writer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="writer_id",
            new_name="writer",
        ),
    ]
